### PR TITLE
test(conformance): Print difference of error codes to a file

### PR DESCRIPTION
**Pull request by kdy1**
**Description:**

This PR make the conformance test suite print the error codes of required errors and excess errors to a file.

**Related issue:**

 - Closes https://github.com/dudykr/stc/issues/709.

### CODE REVIEW

**Comment by infix** [comment]
This is huge, it's going to a save time. is it possible to also log the locations for the errors?

**Comment by kdy1** [comment]
Of course, I'll create another PR

**Comment by kdy1** [comment]
@infix I made https://github.com/dudykr/stc/pull/711

**Comment by infix** [comment]
Thank you!

**Pull request merged**
