### PR TITLE
Feature(analyzer): Implement typeparam validation

### LINKED ISSUE #956: Improve Interface type params
- [ ] Interface type params not validated
   ```ts
   interface A<T extends string> {}
   type a = A<number> // required error, not reported
   ```
- [x] If two interfaces of the same name and the second one has more type params, there's a panic.
  ```ts
  interface A<T extends string> {}
  interface A<T extends number, U extends number> {}
  type a = A<string, number>; // panics
  ```
  ```rs
  thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', 
  crates/stc_ts_file_analyzer/src/analyzer/decl_merging.rs:109:43
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  ```

### PR DESCRIPTION
**Pull request by sunrabbit123**
**Description:**
```ts
interface A<T extends string> {}
type a = A<number> // required error, not reported
```

**Related issue:**

 - Closes #956.

### CODE REVIEW

**Comment by sunrabbit123** [comment]
We're seeing a significant amount of regression, which is something we need to fix.

**Comment by sunrabbit123** [comment]
At the first
```ts
{
    get x() {
      return "boolean" as const;
    },
    y: "string",
  }
```
The above values should be deduced as follows
```ts
{
    readonly x: "boolean";
    y: "string";
}
```
And in `stc`, it's reasoned like this
```
  > {
  |     readonly x: any;
  |     y: "string";
  | }
```

**Comment by sunrabbit123** [comment]
```ts
type A = string[] extends unknown[] ? string : never;
//   ^?
type B<T extends unknown[]> = T;
type C = B<string[]>;
```
is not working

**Comment by sunrabbit123** [comment]
[crates/stc_ts_type_checker/tests/conformance/types/tuple/variadicTuples1](https://github.com/dudykr/stc/pull/1011/files#diff-65ddc58aa56c3d8be495ff4e2bbf6338ed82ca8a5ef48af8e18af77ac27c1c23)

That test has different results in file_analyzer and type_checker.

**Review by kdy1 — APPROVED** [review]
Thank you!

**Comment by kdy1** [comment]
I partially revert this PR with https://github.com/dudykr/stc/pull/1029 because the regression of performance was way too much

**Comment by sunrabbit123** [comment]
In my opinion, the following features are required

https://github.com/dudykr/stc/pull/1029/files#diff-35cb11bec0b1ce7291514626e7a22ef1b38573bd88263c9226163ebb533f79eeL571-L583

**Comment by kdy1** [comment]
Can you retry this PR, but step-by-step this time?

**Comment by sunrabbit123** [comment]
We'll work on them one by one at a later time

**Pull request merged**
