### PR TITLE
Update TypeScript tests and fix outdated test update scripts

### PR DESCRIPTION
**Pull request by hyp3rflow**
**Description:** Update tests: https://github.com/dudykr/stc/issues/179#issuecomment-1302222809

**BREAKING CHANGE:** Some tests..?

**Related issue (if exists):**

### CODE REVIEW

**Comment by hyp3rflow** [comment]
Hi @kdy1! I did update tests as you said and it makes enormous amount of diff on test :|
Is it okay to go? If there are any step to go further or ignore something, feel free to tell me :)

**Comment by kdy1** [comment]
I think it's fine, we should update it anyway. Thank you!

**Comment by hyp3rflow** [comment]
@kdy1 it seems that this PR adds `.stats.rust-debug` file for d.ts test case which is ignored by gitignore. Is there any context for ignoring `*.d.ts`? If it exists, I will open new PR for removing that files.

**Comment by kdy1** [comment]
`.d.ts` is ignored for historical reasons, but it's not relevant anymore so I think we should remove it from `.gitignore`

**Comment by hyp3rflow** [comment]
@kdy1 then I will open new PR for it!

**Comment by kdy1** [comment]
Thank you!

**Pull request merged**
