### PR TITLE
Fix: assign typeparam about conditional 

### PR DESCRIPTION
**Pull request by sunrabbit123**
**Description:**

```ts
interface Contravariant<T> {
  foo: T extends string ? keyof T : number;
}

function f2<A, B extends A>(a: Contravariant<A>, b: Contravariant<B>) {
  a = b;
}
```

### CODE REVIEW

**Review by kdy1 — DISMISSED** [review]
Thanks!

**Comment by kdy1** [comment]
Oh CI failed

**Comment by sunrabbit123** [comment]
I don't understand reason of CI faild
Do you know this reason?

**Comment by kdy1** [comment]
run auto-unignore.sh

2023년 2월 23일 (목) 오후 12:02, 오병진 ***@***.***>님이 작성:

**Comment by sunrabbit123** [comment]
if test contain ignore file, I think that file to ignore should become unignore file
If you examine it, why does ignore file exist?

**Comment by kdy1** [comment]
I didn't get it

**Comment by sunrabbit123** [comment]
ok, first  auto-unignore.sh is test `.*.ts` files?
second, If you test the files that were ignored, Why does `ignore` exist?

**Comment by kdy1** [comment]
Ignored tests failed, but it happen to be pass due to changes in this PR

**Comment by kdy1** [comment]
For first, run the script and commit the result

**Comment by sunrabbit123** [comment]
Oh, I misunderstood the script.
I'm sorry.

**Review by kdy1 — APPROVED** [review]

**Pull request merged**
