### PR TITLE
fix: Allow using types for export assignments

### PR DESCRIPTION
**Pull request by bcheidemann**
**Description:**

Fixes https://github.com/dudykr/stc/issues/717

**BREAKING CHANGE:**

**Related issue (if exists):**

### CODE REVIEW

**Comment by kdy1** [comment]
Can you sign the CLA?

**Review by kdy1 — APPROVED** [review]
Thank you!

**Comment by bcheidemann** [comment]
> Can you sign the CLA?

@kdy1 that's it signed now :) thanks

**Comment by kdy1** [comment]
Thank you!

**Pull request merged**
